-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\HDLAWGNGenerator\GaussianNoiseWithReqVar.vhd
-- Created: 2021-11-25 00:36:10
-- 
-- Generated by MATLAB 9.11 and HDL Coder 3.19
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: GaussianNoiseWithReqVar
-- Source Path: HDLAWGNGenerator/AWGNGenerator/GaussianNoiseWithReqVar
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY GaussianNoiseWithReqVar IS
  PORT( noiseVar                          :   IN    std_logic_vector(21 DOWNTO 0);  -- ufix22_En10
        x0                                :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En11
        awgn                              :   OUT   std_logic_vector(31 DOWNTO 0)  -- sfix32_En15
        );
END GaussianNoiseWithReqVar;


ARCHITECTURE rtl OF GaussianNoiseWithReqVar IS

  -- Signals
  SIGNAL noiseVar_unsigned                : unsigned(21 DOWNTO 0);  -- ufix22_En10
  SIGNAL x0_signed                        : signed(15 DOWNTO 0);  -- sfix16_En11
  SIGNAL Product1_cast                    : signed(22 DOWNTO 0);  -- sfix23_En10
  SIGNAL Product1_mul_temp                : signed(38 DOWNTO 0);  -- sfix39_En21
  SIGNAL Product1_out1                    : signed(37 DOWNTO 0);  -- sfix38_En21
  SIGNAL Data_Type_Conversion_out1        : signed(31 DOWNTO 0);  -- sfix32_En15

BEGIN
  noiseVar_unsigned <= unsigned(noiseVar);

  x0_signed <= signed(x0);

  Product1_cast <= signed(resize(noiseVar_unsigned, 23));
  Product1_mul_temp <= Product1_cast * x0_signed;
  Product1_out1 <= Product1_mul_temp(37 DOWNTO 0);

  Data_Type_Conversion_out1 <= Product1_out1(37 DOWNTO 6);

  awgn <= std_logic_vector(Data_Type_Conversion_out1);

END rtl;

