-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\HDLAWGNGenerator\RangeReconstruction_block.vhd
-- Created: 2021-11-25 00:36:10
-- 
-- Generated by MATLAB 9.11 and HDL Coder 3.19
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: RangeReconstruction_block
-- Source Path: HDLAWGNGenerator/AWGNGenerator/GaussianNoiseWithUnitVar/logImplementation/log/RangeReconstruction
-- Hierarchy Level: 4
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY RangeReconstruction_block IS
  PORT( y_e                               :   IN    std_logic_vector(30 DOWNTO 0);  -- sfix31_En27
        exp_e                             :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        e                                 :   OUT   std_logic_vector(30 DOWNTO 0)  -- ufix31_En24
        );
END RangeReconstruction_block;


ARCHITECTURE rtl OF RangeReconstruction_block IS

  -- Signals
  SIGNAL exp_e_unsigned                   : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Constant_out1                    : signed(32 DOWNTO 0);  -- sfix33_En32
  SIGNAL Product_cast                     : signed(8 DOWNTO 0);  -- sfix9
  SIGNAL Product_mul_temp                 : signed(41 DOWNTO 0);  -- sfix42_En32
  SIGNAL Product_out1                     : signed(40 DOWNTO 0);  -- sfix41_En32
  SIGNAL Product_out1_1                   : signed(34 DOWNTO 0);  -- sfix35_En28
  SIGNAL y_e_signed                       : signed(30 DOWNTO 0);  -- sfix31_En27
  SIGNAL Add1_sub_cast                    : signed(35 DOWNTO 0);  -- sfix36_En28
  SIGNAL Add1_sub_cast_1                  : signed(35 DOWNTO 0);  -- sfix36_En28
  SIGNAL Add1_sub_temp                    : signed(35 DOWNTO 0);  -- sfix36_En28
  SIGNAL Add1_out1                        : unsigned(30 DOWNTO 0);  -- ufix31_En24
  SIGNAL Bit_Shift_out1                   : unsigned(30 DOWNTO 0);  -- ufix31_En24

BEGIN
  exp_e_unsigned <= unsigned(exp_e);

  Constant_out1 <= signed'("010110001011100100001011111111000");

  Product_cast <= signed(resize(exp_e_unsigned, 9));
  Product_mul_temp <= Product_cast * Constant_out1;
  Product_out1 <= Product_mul_temp(40 DOWNTO 0);

  Product_out1_1 <= Product_out1(38 DOWNTO 4);

  y_e_signed <= signed(y_e);

  Add1_sub_cast <= resize(Product_out1_1, 36);
  Add1_sub_cast_1 <= resize(y_e_signed & '0', 36);
  Add1_sub_temp <= Add1_sub_cast - Add1_sub_cast_1;
  Add1_out1 <= unsigned(Add1_sub_temp(34 DOWNTO 4));

  Bit_Shift_out1 <= Add1_out1 sll 1;

  e <= std_logic_vector(Bit_Shift_out1);

END rtl;

