-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\HDLAWGNGenerator\leadingZeroDetector.vhd
-- Created: 2021-11-25 00:36:10
-- 
-- Generated by MATLAB 9.11 and HDL Coder 3.19
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: leadingZeroDetector
-- Source Path: HDLAWGNGenerator/AWGNGenerator/GaussianNoiseWithUnitVar/SqrtImplementation/SqrtEval/RangeReduction/leadingZeroDetector
-- Hierarchy Level: 5
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY leadingZeroDetector IS
  PORT( x                                 :   IN    std_logic_vector(37 DOWNTO 0);  -- ufix38_En31
        exp_f                             :   OUT   std_logic_vector(7 DOWNTO 0)  -- uint8
        );
END leadingZeroDetector;


ARCHITECTURE rtl OF leadingZeroDetector IS

  -- Signals
  SIGNAL x_unsigned                       : unsigned(37 DOWNTO 0);  -- ufix38_En31
  SIGNAL tmp                              : std_logic;
  SIGNAL p124tmp_cast                     : unsigned(75 DOWNTO 0);  -- ufix76_En38
  SIGNAL temp                             : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_1                            : std_logic;
  SIGNAL p121tmp_cast                     : unsigned(75 DOWNTO 0);  -- ufix76_En39
  SIGNAL temp_1                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_2                            : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_3                            : std_logic;
  SIGNAL p117tmp_cast                     : unsigned(75 DOWNTO 0);  -- ufix76_En40
  SIGNAL temp_2                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_4                            : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_5                            : std_logic;
  SIGNAL p113tmp_cast                     : unsigned(75 DOWNTO 0);  -- ufix76_En41
  SIGNAL temp_3                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_6                            : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_7                            : std_logic;
  SIGNAL p109tmp_cast                     : unsigned(75 DOWNTO 0);  -- ufix76_En42
  SIGNAL temp_4                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_8                            : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_9                            : std_logic;
  SIGNAL p105tmp_cast                     : unsigned(75 DOWNTO 0);  -- ufix76_En43
  SIGNAL temp_5                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_10                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_11                           : std_logic;
  SIGNAL p101tmp_cast                     : unsigned(75 DOWNTO 0);  -- ufix76_En44
  SIGNAL temp_6                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_12                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_13                           : std_logic;
  SIGNAL p97tmp_cast                      : unsigned(75 DOWNTO 0);  -- ufix76_En45
  SIGNAL temp_7                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_14                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_15                           : std_logic;
  SIGNAL p93tmp_cast                      : unsigned(75 DOWNTO 0);  -- ufix76_En46
  SIGNAL temp_8                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_16                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_17                           : std_logic;
  SIGNAL p89tmp_cast                      : unsigned(75 DOWNTO 0);  -- ufix76_En47
  SIGNAL temp_9                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_18                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_19                           : std_logic;
  SIGNAL p85tmp_cast                      : unsigned(75 DOWNTO 0);  -- ufix76_En48
  SIGNAL temp_10                          : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_20                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_21                           : std_logic;
  SIGNAL p81tmp_cast                      : unsigned(75 DOWNTO 0);  -- ufix76_En49
  SIGNAL temp_11                          : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_22                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_23                           : std_logic;
  SIGNAL p77tmp_cast                      : unsigned(75 DOWNTO 0);  -- ufix76_En50
  SIGNAL temp_12                          : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_24                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_25                           : std_logic;
  SIGNAL p73tmp_cast                      : unsigned(75 DOWNTO 0);  -- ufix76_En51
  SIGNAL temp_13                          : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_26                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_27                           : std_logic;
  SIGNAL p69tmp_cast                      : unsigned(75 DOWNTO 0);  -- ufix76_En52
  SIGNAL temp_14                          : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_28                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_29                           : std_logic;
  SIGNAL p65tmp_cast                      : unsigned(75 DOWNTO 0);  -- ufix76_En53
  SIGNAL temp_15                          : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_30                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_31                           : std_logic;
  SIGNAL p61tmp_cast                      : unsigned(75 DOWNTO 0);  -- ufix76_En54
  SIGNAL temp_16                          : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_32                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_33                           : std_logic;
  SIGNAL p57tmp_cast                      : unsigned(75 DOWNTO 0);  -- ufix76_En55
  SIGNAL temp_17                          : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_34                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_35                           : std_logic;
  SIGNAL p53tmp_cast                      : unsigned(75 DOWNTO 0);  -- ufix76_En56
  SIGNAL temp_18                          : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_36                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_37                           : std_logic;
  SIGNAL p49tmp_cast                      : unsigned(75 DOWNTO 0);  -- ufix76_En57
  SIGNAL temp_19                          : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_38                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_39                           : std_logic;
  SIGNAL p45tmp_cast                      : unsigned(75 DOWNTO 0);  -- ufix76_En58
  SIGNAL temp_20                          : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_40                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_41                           : std_logic;
  SIGNAL p41tmp_cast                      : unsigned(75 DOWNTO 0);  -- ufix76_En59
  SIGNAL temp_21                          : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_42                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_43                           : std_logic;
  SIGNAL p37tmp_cast                      : unsigned(75 DOWNTO 0);  -- ufix76_En60
  SIGNAL temp_22                          : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_44                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_45                           : std_logic;
  SIGNAL p33tmp_cast                      : unsigned(75 DOWNTO 0);  -- ufix76_En61
  SIGNAL temp_23                          : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_46                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_47                           : std_logic;
  SIGNAL p29tmp_cast                      : unsigned(75 DOWNTO 0);  -- ufix76_En62
  SIGNAL temp_24                          : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_48                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_49                           : std_logic;
  SIGNAL p25tmp_cast                      : unsigned(75 DOWNTO 0);  -- ufix76_En63
  SIGNAL temp_25                          : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_50                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_51                           : std_logic;
  SIGNAL p21tmp_cast                      : unsigned(75 DOWNTO 0);  -- ufix76_En64
  SIGNAL temp_26                          : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_52                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_53                           : std_logic;
  SIGNAL p17tmp_cast                      : unsigned(75 DOWNTO 0);  -- ufix76_En65
  SIGNAL temp_27                          : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_54                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_55                           : std_logic;
  SIGNAL p13tmp_cast                      : unsigned(75 DOWNTO 0);  -- ufix76_En66
  SIGNAL temp_28                          : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_56                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_57                           : std_logic;
  SIGNAL p9tmp_cast                       : unsigned(75 DOWNTO 0);  -- ufix76_En67
  SIGNAL temp_29                          : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_58                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_59                           : std_logic;
  SIGNAL temp_30                          : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_60                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL temp_31                          : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_61                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL exp_f_tmp                        : unsigned(7 DOWNTO 0);  -- uint8

BEGIN
  x_unsigned <= unsigned(x);

  p124tmp_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 76);
  
  tmp <= '1' WHEN p124tmp_cast > unsigned'(X"0000000004000000000") ELSE
      '0';

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector
  -- 
  -- exp_e=31-length(dec2bin(x));
  temp <= to_signed(16#00000000#, 32);

  p121tmp_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 76);
  
  tmp_1 <= '1' WHEN p121tmp_cast > unsigned'(X"0000000008000000000") ELSE
      '0';

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_trueregionp122
  temp_1 <= to_signed(16#0000001E#, 32);

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_falseregionp118
  
  tmp_2 <= temp WHEN tmp = '0' ELSE
      temp_1;

  p117tmp_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 76);
  
  tmp_3 <= '1' WHEN p117tmp_cast > unsigned'(X"0000000010000000000") ELSE
      '0';

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_trueregionp118
  temp_2 <= to_signed(16#0000001D#, 32);

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_falseregionp114
  
  tmp_4 <= tmp_2 WHEN tmp_1 = '0' ELSE
      temp_2;

  p113tmp_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 76);
  
  tmp_5 <= '1' WHEN p113tmp_cast > unsigned'(X"0000000020000000000") ELSE
      '0';

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_trueregionp114
  temp_3 <= to_signed(16#0000001C#, 32);

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_falseregionp110
  
  tmp_6 <= tmp_4 WHEN tmp_3 = '0' ELSE
      temp_3;

  p109tmp_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 76);
  
  tmp_7 <= '1' WHEN p109tmp_cast > unsigned'(X"0000000040000000000") ELSE
      '0';

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_trueregionp110
  temp_4 <= to_signed(16#0000001B#, 32);

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_falseregionp106
  
  tmp_8 <= tmp_6 WHEN tmp_5 = '0' ELSE
      temp_4;

  p105tmp_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 76);
  
  tmp_9 <= '1' WHEN p105tmp_cast > unsigned'(X"0000000080000000000") ELSE
      '0';

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_trueregionp106
  temp_5 <= to_signed(16#0000001A#, 32);

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_falseregionp102
  
  tmp_10 <= tmp_8 WHEN tmp_7 = '0' ELSE
      temp_5;

  p101tmp_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 76);
  
  tmp_11 <= '1' WHEN p101tmp_cast > unsigned'(X"0000000100000000000") ELSE
      '0';

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_trueregionp102
  temp_6 <= to_signed(16#00000019#, 32);

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_falseregionp98
  
  tmp_12 <= tmp_10 WHEN tmp_9 = '0' ELSE
      temp_6;

  p97tmp_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 76);
  
  tmp_13 <= '1' WHEN p97tmp_cast > unsigned'(X"0000000200000000000") ELSE
      '0';

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_trueregionp98
  temp_7 <= to_signed(16#00000018#, 32);

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_falseregionp94
  
  tmp_14 <= tmp_12 WHEN tmp_11 = '0' ELSE
      temp_7;

  p93tmp_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 76);
  
  tmp_15 <= '1' WHEN p93tmp_cast > unsigned'(X"0000000400000000000") ELSE
      '0';

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_trueregionp94
  temp_8 <= to_signed(16#00000017#, 32);

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_falseregionp90
  
  tmp_16 <= tmp_14 WHEN tmp_13 = '0' ELSE
      temp_8;

  p89tmp_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 76);
  
  tmp_17 <= '1' WHEN p89tmp_cast > unsigned'(X"0000000800000000000") ELSE
      '0';

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_trueregionp90
  temp_9 <= to_signed(16#00000016#, 32);

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_falseregionp86
  
  tmp_18 <= tmp_16 WHEN tmp_15 = '0' ELSE
      temp_9;

  p85tmp_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 76);
  
  tmp_19 <= '1' WHEN p85tmp_cast > unsigned'(X"0000001000000000000") ELSE
      '0';

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_trueregionp86
  temp_10 <= to_signed(16#00000015#, 32);

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_falseregionp82
  
  tmp_20 <= tmp_18 WHEN tmp_17 = '0' ELSE
      temp_10;

  p81tmp_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 76);
  
  tmp_21 <= '1' WHEN p81tmp_cast > unsigned'(X"0000002000000000000") ELSE
      '0';

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_trueregionp82
  temp_11 <= to_signed(16#00000014#, 32);

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_falseregionp78
  
  tmp_22 <= tmp_20 WHEN tmp_19 = '0' ELSE
      temp_11;

  p77tmp_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 76);
  
  tmp_23 <= '1' WHEN p77tmp_cast > unsigned'(X"0000004000000000000") ELSE
      '0';

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_trueregionp78
  temp_12 <= to_signed(16#00000013#, 32);

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_falseregionp74
  
  tmp_24 <= tmp_22 WHEN tmp_21 = '0' ELSE
      temp_12;

  p73tmp_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 76);
  
  tmp_25 <= '1' WHEN p73tmp_cast > unsigned'(X"0000008000000000000") ELSE
      '0';

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_trueregionp74
  temp_13 <= to_signed(16#00000012#, 32);

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_falseregionp70
  
  tmp_26 <= tmp_24 WHEN tmp_23 = '0' ELSE
      temp_13;

  p69tmp_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 76);
  
  tmp_27 <= '1' WHEN p69tmp_cast > unsigned'(X"0000010000000000000") ELSE
      '0';

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_trueregionp70
  temp_14 <= to_signed(16#00000011#, 32);

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_falseregionp66
  
  tmp_28 <= tmp_26 WHEN tmp_25 = '0' ELSE
      temp_14;

  p65tmp_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 76);
  
  tmp_29 <= '1' WHEN p65tmp_cast > unsigned'(X"0000020000000000000") ELSE
      '0';

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_trueregionp66
  temp_15 <= to_signed(16#00000010#, 32);

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_falseregionp62
  
  tmp_30 <= tmp_28 WHEN tmp_27 = '0' ELSE
      temp_15;

  p61tmp_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 76);
  
  tmp_31 <= '1' WHEN p61tmp_cast > unsigned'(X"0000040000000000000") ELSE
      '0';

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_trueregionp62
  temp_16 <= to_signed(16#0000000F#, 32);

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_falseregionp58
  
  tmp_32 <= tmp_30 WHEN tmp_29 = '0' ELSE
      temp_16;

  p57tmp_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 76);
  
  tmp_33 <= '1' WHEN p57tmp_cast > unsigned'(X"0000080000000000000") ELSE
      '0';

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_trueregionp58
  temp_17 <= to_signed(16#0000000E#, 32);

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_falseregionp54
  
  tmp_34 <= tmp_32 WHEN tmp_31 = '0' ELSE
      temp_17;

  p53tmp_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 76);
  
  tmp_35 <= '1' WHEN p53tmp_cast > unsigned'(X"0000100000000000000") ELSE
      '0';

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_trueregionp54
  temp_18 <= to_signed(16#0000000D#, 32);

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_falseregionp50
  
  tmp_36 <= tmp_34 WHEN tmp_33 = '0' ELSE
      temp_18;

  p49tmp_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 76);
  
  tmp_37 <= '1' WHEN p49tmp_cast > unsigned'(X"0000200000000000000") ELSE
      '0';

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_trueregionp50
  temp_19 <= to_signed(16#0000000C#, 32);

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_falseregionp46
  
  tmp_38 <= tmp_36 WHEN tmp_35 = '0' ELSE
      temp_19;

  p45tmp_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 76);
  
  tmp_39 <= '1' WHEN p45tmp_cast > unsigned'(X"0000400000000000000") ELSE
      '0';

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_trueregionp46
  temp_20 <= to_signed(16#0000000B#, 32);

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_falseregionp42
  
  tmp_40 <= tmp_38 WHEN tmp_37 = '0' ELSE
      temp_20;

  p41tmp_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 76);
  
  tmp_41 <= '1' WHEN p41tmp_cast > unsigned'(X"0000800000000000000") ELSE
      '0';

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_trueregionp42
  temp_21 <= to_signed(16#0000000A#, 32);

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_falseregionp38
  
  tmp_42 <= tmp_40 WHEN tmp_39 = '0' ELSE
      temp_21;

  p37tmp_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 76);
  
  tmp_43 <= '1' WHEN p37tmp_cast > unsigned'(X"0001000000000000000") ELSE
      '0';

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_trueregionp38
  temp_22 <= to_signed(16#00000009#, 32);

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_falseregionp34
  
  tmp_44 <= tmp_42 WHEN tmp_41 = '0' ELSE
      temp_22;

  p33tmp_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 76);
  
  tmp_45 <= '1' WHEN p33tmp_cast > unsigned'(X"0002000000000000000") ELSE
      '0';

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_trueregionp34
  temp_23 <= to_signed(16#00000008#, 32);

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_falseregionp30
  
  tmp_46 <= tmp_44 WHEN tmp_43 = '0' ELSE
      temp_23;

  p29tmp_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 76);
  
  tmp_47 <= '1' WHEN p29tmp_cast > unsigned'(X"0004000000000000000") ELSE
      '0';

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_trueregionp30
  temp_24 <= to_signed(16#00000007#, 32);

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_falseregionp26
  
  tmp_48 <= tmp_46 WHEN tmp_45 = '0' ELSE
      temp_24;

  p25tmp_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 76);
  
  tmp_49 <= '1' WHEN p25tmp_cast > unsigned'(X"0008000000000000000") ELSE
      '0';

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_trueregionp26
  temp_25 <= to_signed(16#00000006#, 32);

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_falseregionp22
  
  tmp_50 <= tmp_48 WHEN tmp_47 = '0' ELSE
      temp_25;

  p21tmp_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 76);
  
  tmp_51 <= '1' WHEN p21tmp_cast > unsigned'(X"0010000000000000000") ELSE
      '0';

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_trueregionp22
  temp_26 <= to_signed(16#00000005#, 32);

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_falseregionp18
  
  tmp_52 <= tmp_50 WHEN tmp_49 = '0' ELSE
      temp_26;

  p17tmp_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 76);
  
  tmp_53 <= '1' WHEN p17tmp_cast > unsigned'(X"0020000000000000000") ELSE
      '0';

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_trueregionp18
  temp_27 <= to_signed(16#00000004#, 32);

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_falseregionp14
  
  tmp_54 <= tmp_52 WHEN tmp_51 = '0' ELSE
      temp_27;

  p13tmp_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 76);
  
  tmp_55 <= '1' WHEN p13tmp_cast > unsigned'(X"0040000000000000000") ELSE
      '0';

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_trueregionp14
  temp_28 <= to_signed(16#00000003#, 32);

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_falseregionp10
  
  tmp_56 <= tmp_54 WHEN tmp_53 = '0' ELSE
      temp_28;

  p9tmp_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 76);
  
  tmp_57 <= '1' WHEN p9tmp_cast > unsigned'(X"0080000000000000000") ELSE
      '0';

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_trueregionp10
  temp_29 <= to_signed(16#00000002#, 32);

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_falseregionp6
  
  tmp_58 <= tmp_56 WHEN tmp_55 = '0' ELSE
      temp_29;

  -- else
  -- 
  --     while( )
  -- 
  --         temp = temp+1;
  -- 
  --         flag()=flag()*2;
  -- 
  --     end
  -- 
  -- end
  -- 
  -- 
  -- 
  -- end
  
  tmp_59 <= '1' WHEN x_unsigned = to_unsigned(0, 38) ELSE
      '0';

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_trueregionp6
  temp_30 <= to_signed(16#00000001#, 32);

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_falseregionp2
  
  tmp_60 <= tmp_58 WHEN tmp_57 = '0' ELSE
      temp_30;

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_trueregionp2
  temp_31 <= to_signed(16#0000001F#, 32);

  
  tmp_61 <= tmp_60 WHEN tmp_59 = '0' ELSE
      temp_31;

  exp_f_tmp <= unsigned(tmp_61(7 DOWNTO 0));

  exp_f <= std_logic_vector(exp_f_tmp);

END rtl;

