-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\HDLAWGNGenerator\leadingZeroDetector_block.vhd
-- Created: 2021-11-25 00:36:10
-- 
-- Generated by MATLAB 9.11 and HDL Coder 3.19
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: leadingZeroDetector_block
-- Source Path: HDLAWGNGenerator/AWGNGenerator/GaussianNoiseWithUnitVar/logImplementation/log/RangeReduction/leadingZeroDetector
-- Hierarchy Level: 5
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY leadingZeroDetector_block IS
  PORT( x                                 :   IN    std_logic_vector(47 DOWNTO 0);  -- ufix48_En48
        exp_e                             :   OUT   std_logic_vector(7 DOWNTO 0)  -- uint8
        );
END leadingZeroDetector_block;


ARCHITECTURE rtl OF leadingZeroDetector_block IS

  -- Signals
  SIGNAL x_unsigned                       : unsigned(47 DOWNTO 0);  -- ufix48_En48
  SIGNAL tmp                              : std_logic;
  SIGNAL p196tmp_cast                     : unsigned(95 DOWNTO 0);  -- ufix96_En47
  SIGNAL temp                             : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_1                            : std_logic;
  SIGNAL p193tmp_cast                     : unsigned(95 DOWNTO 0);  -- ufix96_En48
  SIGNAL temp_1                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_2                            : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_3                            : std_logic;
  SIGNAL p189tmp_cast                     : unsigned(95 DOWNTO 0);  -- ufix96_En49
  SIGNAL temp_2                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_4                            : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_5                            : std_logic;
  SIGNAL p185tmp_cast                     : unsigned(95 DOWNTO 0);  -- ufix96_En50
  SIGNAL temp_3                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_6                            : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_7                            : std_logic;
  SIGNAL p181tmp_cast                     : unsigned(95 DOWNTO 0);  -- ufix96_En51
  SIGNAL temp_4                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_8                            : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_9                            : std_logic;
  SIGNAL p177tmp_cast                     : unsigned(95 DOWNTO 0);  -- ufix96_En52
  SIGNAL temp_5                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_10                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_11                           : std_logic;
  SIGNAL p173tmp_cast                     : unsigned(95 DOWNTO 0);  -- ufix96_En53
  SIGNAL temp_6                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_12                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_13                           : std_logic;
  SIGNAL p169tmp_cast                     : unsigned(95 DOWNTO 0);  -- ufix96_En54
  SIGNAL temp_7                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_14                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_15                           : std_logic;
  SIGNAL p165tmp_cast                     : unsigned(95 DOWNTO 0);  -- ufix96_En55
  SIGNAL temp_8                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_16                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_17                           : std_logic;
  SIGNAL p161tmp_cast                     : unsigned(95 DOWNTO 0);  -- ufix96_En56
  SIGNAL temp_9                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_18                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_19                           : std_logic;
  SIGNAL p157tmp_cast                     : unsigned(95 DOWNTO 0);  -- ufix96_En57
  SIGNAL temp_10                          : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_20                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_21                           : std_logic;
  SIGNAL p153tmp_cast                     : unsigned(95 DOWNTO 0);  -- ufix96_En58
  SIGNAL temp_11                          : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_22                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_23                           : std_logic;
  SIGNAL p149tmp_cast                     : unsigned(95 DOWNTO 0);  -- ufix96_En59
  SIGNAL temp_12                          : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_24                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_25                           : std_logic;
  SIGNAL p145tmp_cast                     : unsigned(95 DOWNTO 0);  -- ufix96_En60
  SIGNAL temp_13                          : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_26                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_27                           : std_logic;
  SIGNAL p141tmp_cast                     : unsigned(95 DOWNTO 0);  -- ufix96_En61
  SIGNAL temp_14                          : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_28                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_29                           : std_logic;
  SIGNAL p137tmp_cast                     : unsigned(95 DOWNTO 0);  -- ufix96_En62
  SIGNAL temp_15                          : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_30                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_31                           : std_logic;
  SIGNAL p133tmp_cast                     : unsigned(95 DOWNTO 0);  -- ufix96_En63
  SIGNAL temp_16                          : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_32                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_33                           : std_logic;
  SIGNAL p129tmp_cast                     : unsigned(95 DOWNTO 0);  -- ufix96_En64
  SIGNAL temp_17                          : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_34                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_35                           : std_logic;
  SIGNAL p125tmp_cast                     : unsigned(95 DOWNTO 0);  -- ufix96_En65
  SIGNAL temp_18                          : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_36                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_37                           : std_logic;
  SIGNAL p121tmp_cast                     : unsigned(95 DOWNTO 0);  -- ufix96_En66
  SIGNAL temp_19                          : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_38                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_39                           : std_logic;
  SIGNAL p117tmp_cast                     : unsigned(95 DOWNTO 0);  -- ufix96_En67
  SIGNAL temp_20                          : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_40                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_41                           : std_logic;
  SIGNAL p113tmp_cast                     : unsigned(95 DOWNTO 0);  -- ufix96_En68
  SIGNAL temp_21                          : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_42                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_43                           : std_logic;
  SIGNAL p109tmp_cast                     : unsigned(95 DOWNTO 0);  -- ufix96_En69
  SIGNAL temp_22                          : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_44                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_45                           : std_logic;
  SIGNAL p105tmp_cast                     : unsigned(95 DOWNTO 0);  -- ufix96_En70
  SIGNAL temp_23                          : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_46                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_47                           : std_logic;
  SIGNAL p101tmp_cast                     : unsigned(95 DOWNTO 0);  -- ufix96_En71
  SIGNAL temp_24                          : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_48                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_49                           : std_logic;
  SIGNAL p97tmp_cast                      : unsigned(95 DOWNTO 0);  -- ufix96_En72
  SIGNAL temp_25                          : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_50                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_51                           : std_logic;
  SIGNAL p93tmp_cast                      : unsigned(95 DOWNTO 0);  -- ufix96_En73
  SIGNAL temp_26                          : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_52                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_53                           : std_logic;
  SIGNAL p89tmp_cast                      : unsigned(95 DOWNTO 0);  -- ufix96_En74
  SIGNAL temp_27                          : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_54                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_55                           : std_logic;
  SIGNAL p85tmp_cast                      : unsigned(95 DOWNTO 0);  -- ufix96_En75
  SIGNAL temp_28                          : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_56                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_57                           : std_logic;
  SIGNAL p81tmp_cast                      : unsigned(95 DOWNTO 0);  -- ufix96_En76
  SIGNAL temp_29                          : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_58                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_59                           : std_logic;
  SIGNAL p77tmp_cast                      : unsigned(95 DOWNTO 0);  -- ufix96_En77
  SIGNAL temp_30                          : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_60                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_61                           : std_logic;
  SIGNAL p73tmp_cast                      : unsigned(95 DOWNTO 0);  -- ufix96_En78
  SIGNAL temp_31                          : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_62                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_63                           : std_logic;
  SIGNAL p69tmp_cast                      : unsigned(95 DOWNTO 0);  -- ufix96_En79
  SIGNAL temp_32                          : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_64                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_65                           : std_logic;
  SIGNAL p65tmp_cast                      : unsigned(95 DOWNTO 0);  -- ufix96_En80
  SIGNAL temp_33                          : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_66                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_67                           : std_logic;
  SIGNAL p61tmp_cast                      : unsigned(95 DOWNTO 0);  -- ufix96_En81
  SIGNAL temp_34                          : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_68                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_69                           : std_logic;
  SIGNAL p57tmp_cast                      : unsigned(95 DOWNTO 0);  -- ufix96_En82
  SIGNAL temp_35                          : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_70                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_71                           : std_logic;
  SIGNAL p53tmp_cast                      : unsigned(95 DOWNTO 0);  -- ufix96_En83
  SIGNAL temp_36                          : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_72                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_73                           : std_logic;
  SIGNAL p49tmp_cast                      : unsigned(95 DOWNTO 0);  -- ufix96_En84
  SIGNAL temp_37                          : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_74                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_75                           : std_logic;
  SIGNAL p45tmp_cast                      : unsigned(95 DOWNTO 0);  -- ufix96_En85
  SIGNAL temp_38                          : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_76                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_77                           : std_logic;
  SIGNAL p41tmp_cast                      : unsigned(95 DOWNTO 0);  -- ufix96_En86
  SIGNAL temp_39                          : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_78                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_79                           : std_logic;
  SIGNAL p37tmp_cast                      : unsigned(95 DOWNTO 0);  -- ufix96_En87
  SIGNAL temp_40                          : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_80                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_81                           : std_logic;
  SIGNAL p33tmp_cast                      : unsigned(95 DOWNTO 0);  -- ufix96_En88
  SIGNAL temp_41                          : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_82                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_83                           : std_logic;
  SIGNAL p29tmp_cast                      : unsigned(95 DOWNTO 0);  -- ufix96_En89
  SIGNAL temp_42                          : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_84                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_85                           : std_logic;
  SIGNAL p25tmp_cast                      : unsigned(95 DOWNTO 0);  -- ufix96_En90
  SIGNAL temp_43                          : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_86                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_87                           : std_logic;
  SIGNAL p21tmp_cast                      : unsigned(95 DOWNTO 0);  -- ufix96_En91
  SIGNAL temp_44                          : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_88                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_89                           : std_logic;
  SIGNAL p17tmp_cast                      : unsigned(95 DOWNTO 0);  -- ufix96_En92
  SIGNAL temp_45                          : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_90                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_91                           : std_logic;
  SIGNAL p13tmp_cast                      : unsigned(95 DOWNTO 0);  -- ufix96_En93
  SIGNAL temp_46                          : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_92                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_93                           : std_logic;
  SIGNAL p9tmp_cast                       : unsigned(95 DOWNTO 0);  -- ufix96_En94
  SIGNAL temp_47                          : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_94                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_95                           : std_logic;
  SIGNAL temp_48                          : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_96                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL temp_49                          : signed(31 DOWNTO 0);  -- int32
  SIGNAL tmp_97                           : signed(31 DOWNTO 0);  -- int32
  SIGNAL exp_e_tmp                        : unsigned(7 DOWNTO 0);  -- uint8

BEGIN
  x_unsigned <= unsigned(x);

  p196tmp_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 96);
  
  tmp <= '1' WHEN p196tmp_cast > unsigned'(X"000000000000800000000000") ELSE
      '0';

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector
  temp <= to_signed(16#00000000#, 32);

  p193tmp_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 96);
  
  tmp_1 <= '1' WHEN p193tmp_cast > unsigned'(X"000000000001000000000000") ELSE
      '0';

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_trueregionp194
  temp_1 <= to_signed(16#00000030#, 32);

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_falseregionp190
  
  tmp_2 <= temp WHEN tmp = '0' ELSE
      temp_1;

  p189tmp_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 96);
  
  tmp_3 <= '1' WHEN p189tmp_cast > unsigned'(X"000000000002000000000000") ELSE
      '0';

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_trueregionp190
  temp_2 <= to_signed(16#0000002F#, 32);

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_falseregionp186
  
  tmp_4 <= tmp_2 WHEN tmp_1 = '0' ELSE
      temp_2;

  p185tmp_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 96);
  
  tmp_5 <= '1' WHEN p185tmp_cast > unsigned'(X"000000000004000000000000") ELSE
      '0';

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_trueregionp186
  temp_3 <= to_signed(16#0000002E#, 32);

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_falseregionp182
  
  tmp_6 <= tmp_4 WHEN tmp_3 = '0' ELSE
      temp_3;

  p181tmp_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 96);
  
  tmp_7 <= '1' WHEN p181tmp_cast > unsigned'(X"000000000008000000000000") ELSE
      '0';

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_trueregionp182
  temp_4 <= to_signed(16#0000002D#, 32);

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_falseregionp178
  
  tmp_8 <= tmp_6 WHEN tmp_5 = '0' ELSE
      temp_4;

  p177tmp_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 96);
  
  tmp_9 <= '1' WHEN p177tmp_cast > unsigned'(X"000000000010000000000000") ELSE
      '0';

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_trueregionp178
  temp_5 <= to_signed(16#0000002C#, 32);

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_falseregionp174
  
  tmp_10 <= tmp_8 WHEN tmp_7 = '0' ELSE
      temp_5;

  p173tmp_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 96);
  
  tmp_11 <= '1' WHEN p173tmp_cast > unsigned'(X"000000000020000000000000") ELSE
      '0';

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_trueregionp174
  temp_6 <= to_signed(16#0000002B#, 32);

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_falseregionp170
  
  tmp_12 <= tmp_10 WHEN tmp_9 = '0' ELSE
      temp_6;

  p169tmp_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 96);
  
  tmp_13 <= '1' WHEN p169tmp_cast > unsigned'(X"000000000040000000000000") ELSE
      '0';

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_trueregionp170
  temp_7 <= to_signed(16#0000002A#, 32);

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_falseregionp166
  
  tmp_14 <= tmp_12 WHEN tmp_11 = '0' ELSE
      temp_7;

  p165tmp_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 96);
  
  tmp_15 <= '1' WHEN p165tmp_cast > unsigned'(X"000000000080000000000000") ELSE
      '0';

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_trueregionp166
  temp_8 <= to_signed(16#00000029#, 32);

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_falseregionp162
  
  tmp_16 <= tmp_14 WHEN tmp_13 = '0' ELSE
      temp_8;

  p161tmp_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 96);
  
  tmp_17 <= '1' WHEN p161tmp_cast > unsigned'(X"000000000100000000000000") ELSE
      '0';

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_trueregionp162
  temp_9 <= to_signed(16#00000028#, 32);

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_falseregionp158
  
  tmp_18 <= tmp_16 WHEN tmp_15 = '0' ELSE
      temp_9;

  p157tmp_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 96);
  
  tmp_19 <= '1' WHEN p157tmp_cast > unsigned'(X"000000000200000000000000") ELSE
      '0';

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_trueregionp158
  temp_10 <= to_signed(16#00000027#, 32);

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_falseregionp154
  
  tmp_20 <= tmp_18 WHEN tmp_17 = '0' ELSE
      temp_10;

  p153tmp_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 96);
  
  tmp_21 <= '1' WHEN p153tmp_cast > unsigned'(X"000000000400000000000000") ELSE
      '0';

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_trueregionp154
  temp_11 <= to_signed(16#00000008#, 32);

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_falseregionp150
  
  tmp_22 <= tmp_20 WHEN tmp_19 = '0' ELSE
      temp_11;

  p149tmp_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 96);
  
  tmp_23 <= '1' WHEN p149tmp_cast > unsigned'(X"000000000800000000000000") ELSE
      '0';

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_trueregionp150
  temp_12 <= to_signed(16#00000025#, 32);

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_falseregionp146
  
  tmp_24 <= tmp_22 WHEN tmp_21 = '0' ELSE
      temp_12;

  p145tmp_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 96);
  
  tmp_25 <= '1' WHEN p145tmp_cast > unsigned'(X"000000001000000000000000") ELSE
      '0';

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_trueregionp146
  temp_13 <= to_signed(16#00000024#, 32);

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_falseregionp142
  
  tmp_26 <= tmp_24 WHEN tmp_23 = '0' ELSE
      temp_13;

  p141tmp_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 96);
  
  tmp_27 <= '1' WHEN p141tmp_cast > unsigned'(X"000000002000000000000000") ELSE
      '0';

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_trueregionp142
  temp_14 <= to_signed(16#00000023#, 32);

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_falseregionp138
  
  tmp_28 <= tmp_26 WHEN tmp_25 = '0' ELSE
      temp_14;

  p137tmp_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 96);
  
  tmp_29 <= '1' WHEN p137tmp_cast > unsigned'(X"000000004000000000000000") ELSE
      '0';

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_trueregionp138
  temp_15 <= to_signed(16#00000022#, 32);

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_falseregionp134
  
  tmp_30 <= tmp_28 WHEN tmp_27 = '0' ELSE
      temp_15;

  p133tmp_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 96);
  
  tmp_31 <= '1' WHEN p133tmp_cast > unsigned'(X"000000008000000000000000") ELSE
      '0';

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_trueregionp134
  temp_16 <= to_signed(16#00000021#, 32);

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_falseregionp130
  
  tmp_32 <= tmp_30 WHEN tmp_29 = '0' ELSE
      temp_16;

  p129tmp_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 96);
  
  tmp_33 <= '1' WHEN p129tmp_cast > unsigned'(X"000000010000000000000000") ELSE
      '0';

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_trueregionp130
  temp_17 <= to_signed(16#00000020#, 32);

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_falseregionp126
  
  tmp_34 <= tmp_32 WHEN tmp_31 = '0' ELSE
      temp_17;

  p125tmp_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 96);
  
  tmp_35 <= '1' WHEN p125tmp_cast > unsigned'(X"000000020000000000000000") ELSE
      '0';

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_trueregionp126
  temp_18 <= to_signed(16#0000001F#, 32);

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_falseregionp122
  
  tmp_36 <= tmp_34 WHEN tmp_33 = '0' ELSE
      temp_18;

  p121tmp_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 96);
  
  tmp_37 <= '1' WHEN p121tmp_cast > unsigned'(X"000000040000000000000000") ELSE
      '0';

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_trueregionp122
  temp_19 <= to_signed(16#0000001E#, 32);

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_falseregionp118
  
  tmp_38 <= tmp_36 WHEN tmp_35 = '0' ELSE
      temp_19;

  p117tmp_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 96);
  
  tmp_39 <= '1' WHEN p117tmp_cast > unsigned'(X"000000080000000000000000") ELSE
      '0';

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_trueregionp118
  temp_20 <= to_signed(16#0000001D#, 32);

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_falseregionp114
  
  tmp_40 <= tmp_38 WHEN tmp_37 = '0' ELSE
      temp_20;

  p113tmp_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 96);
  
  tmp_41 <= '1' WHEN p113tmp_cast > unsigned'(X"000000100000000000000000") ELSE
      '0';

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_trueregionp114
  temp_21 <= to_signed(16#0000001C#, 32);

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_falseregionp110
  
  tmp_42 <= tmp_40 WHEN tmp_39 = '0' ELSE
      temp_21;

  p109tmp_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 96);
  
  tmp_43 <= '1' WHEN p109tmp_cast > unsigned'(X"000000200000000000000000") ELSE
      '0';

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_trueregionp110
  temp_22 <= to_signed(16#0000001B#, 32);

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_falseregionp106
  
  tmp_44 <= tmp_42 WHEN tmp_41 = '0' ELSE
      temp_22;

  p105tmp_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 96);
  
  tmp_45 <= '1' WHEN p105tmp_cast > unsigned'(X"000000400000000000000000") ELSE
      '0';

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_trueregionp106
  temp_23 <= to_signed(16#0000001A#, 32);

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_falseregionp102
  
  tmp_46 <= tmp_44 WHEN tmp_43 = '0' ELSE
      temp_23;

  p101tmp_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 96);
  
  tmp_47 <= '1' WHEN p101tmp_cast > unsigned'(X"000000800000000000000000") ELSE
      '0';

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_trueregionp102
  temp_24 <= to_signed(16#00000019#, 32);

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_falseregionp98
  
  tmp_48 <= tmp_46 WHEN tmp_45 = '0' ELSE
      temp_24;

  p97tmp_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 96);
  
  tmp_49 <= '1' WHEN p97tmp_cast > unsigned'(X"000001000000000000000000") ELSE
      '0';

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_trueregionp98
  temp_25 <= to_signed(16#00000018#, 32);

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_falseregionp94
  
  tmp_50 <= tmp_48 WHEN tmp_47 = '0' ELSE
      temp_25;

  p93tmp_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 96);
  
  tmp_51 <= '1' WHEN p93tmp_cast > unsigned'(X"000002000000000000000000") ELSE
      '0';

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_trueregionp94
  temp_26 <= to_signed(16#00000017#, 32);

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_falseregionp90
  
  tmp_52 <= tmp_50 WHEN tmp_49 = '0' ELSE
      temp_26;

  p89tmp_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 96);
  
  tmp_53 <= '1' WHEN p89tmp_cast > unsigned'(X"000004000000000000000000") ELSE
      '0';

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_trueregionp90
  temp_27 <= to_signed(16#00000016#, 32);

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_falseregionp86
  
  tmp_54 <= tmp_52 WHEN tmp_51 = '0' ELSE
      temp_27;

  p85tmp_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 96);
  
  tmp_55 <= '1' WHEN p85tmp_cast > unsigned'(X"000008000000000000000000") ELSE
      '0';

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_trueregionp86
  temp_28 <= to_signed(16#00000015#, 32);

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_falseregionp82
  
  tmp_56 <= tmp_54 WHEN tmp_53 = '0' ELSE
      temp_28;

  p81tmp_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 96);
  
  tmp_57 <= '1' WHEN p81tmp_cast > unsigned'(X"000010000000000000000000") ELSE
      '0';

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_trueregionp82
  temp_29 <= to_signed(16#00000014#, 32);

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_falseregionp78
  
  tmp_58 <= tmp_56 WHEN tmp_55 = '0' ELSE
      temp_29;

  p77tmp_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 96);
  
  tmp_59 <= '1' WHEN p77tmp_cast > unsigned'(X"000020000000000000000000") ELSE
      '0';

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_trueregionp78
  temp_30 <= to_signed(16#00000013#, 32);

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_falseregionp74
  
  tmp_60 <= tmp_58 WHEN tmp_57 = '0' ELSE
      temp_30;

  p73tmp_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 96);
  
  tmp_61 <= '1' WHEN p73tmp_cast > unsigned'(X"000040000000000000000000") ELSE
      '0';

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_trueregionp74
  temp_31 <= to_signed(16#00000012#, 32);

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_falseregionp70
  
  tmp_62 <= tmp_60 WHEN tmp_59 = '0' ELSE
      temp_31;

  p69tmp_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 96);
  
  tmp_63 <= '1' WHEN p69tmp_cast > unsigned'(X"000080000000000000000000") ELSE
      '0';

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_trueregionp70
  temp_32 <= to_signed(16#00000011#, 32);

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_falseregionp66
  
  tmp_64 <= tmp_62 WHEN tmp_61 = '0' ELSE
      temp_32;

  p65tmp_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 96);
  
  tmp_65 <= '1' WHEN p65tmp_cast > unsigned'(X"000100000000000000000000") ELSE
      '0';

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_trueregionp66
  temp_33 <= to_signed(16#00000010#, 32);

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_falseregionp62
  
  tmp_66 <= tmp_64 WHEN tmp_63 = '0' ELSE
      temp_33;

  p61tmp_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 96);
  
  tmp_67 <= '1' WHEN p61tmp_cast > unsigned'(X"000200000000000000000000") ELSE
      '0';

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_trueregionp62
  temp_34 <= to_signed(16#0000000F#, 32);

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_falseregionp58
  
  tmp_68 <= tmp_66 WHEN tmp_65 = '0' ELSE
      temp_34;

  p57tmp_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 96);
  
  tmp_69 <= '1' WHEN p57tmp_cast > unsigned'(X"000400000000000000000000") ELSE
      '0';

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_trueregionp58
  temp_35 <= to_signed(16#0000000E#, 32);

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_falseregionp54
  
  tmp_70 <= tmp_68 WHEN tmp_67 = '0' ELSE
      temp_35;

  p53tmp_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 96);
  
  tmp_71 <= '1' WHEN p53tmp_cast > unsigned'(X"000800000000000000000000") ELSE
      '0';

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_trueregionp54
  temp_36 <= to_signed(16#0000000D#, 32);

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_falseregionp50
  
  tmp_72 <= tmp_70 WHEN tmp_69 = '0' ELSE
      temp_36;

  p49tmp_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 96);
  
  tmp_73 <= '1' WHEN p49tmp_cast > unsigned'(X"001000000000000000000000") ELSE
      '0';

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_trueregionp50
  temp_37 <= to_signed(16#0000000C#, 32);

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_falseregionp46
  
  tmp_74 <= tmp_72 WHEN tmp_71 = '0' ELSE
      temp_37;

  p45tmp_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 96);
  
  tmp_75 <= '1' WHEN p45tmp_cast > unsigned'(X"002000000000000000000000") ELSE
      '0';

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_trueregionp46
  temp_38 <= to_signed(16#0000000B#, 32);

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_falseregionp42
  
  tmp_76 <= tmp_74 WHEN tmp_73 = '0' ELSE
      temp_38;

  p41tmp_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 96);
  
  tmp_77 <= '1' WHEN p41tmp_cast > unsigned'(X"004000000000000000000000") ELSE
      '0';

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_trueregionp42
  temp_39 <= to_signed(16#0000000A#, 32);

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_falseregionp38
  
  tmp_78 <= tmp_76 WHEN tmp_75 = '0' ELSE
      temp_39;

  p37tmp_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 96);
  
  tmp_79 <= '1' WHEN p37tmp_cast > unsigned'(X"008000000000000000000000") ELSE
      '0';

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_trueregionp38
  temp_40 <= to_signed(16#00000009#, 32);

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_falseregionp34
  
  tmp_80 <= tmp_78 WHEN tmp_77 = '0' ELSE
      temp_40;

  p33tmp_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 96);
  
  tmp_81 <= '1' WHEN p33tmp_cast > unsigned'(X"010000000000000000000000") ELSE
      '0';

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_trueregionp34
  temp_41 <= to_signed(16#00000008#, 32);

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_falseregionp30
  
  tmp_82 <= tmp_80 WHEN tmp_79 = '0' ELSE
      temp_41;

  p29tmp_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 96);
  
  tmp_83 <= '1' WHEN p29tmp_cast > unsigned'(X"020000000000000000000000") ELSE
      '0';

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_trueregionp30
  temp_42 <= to_signed(16#00000007#, 32);

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_falseregionp26
  
  tmp_84 <= tmp_82 WHEN tmp_81 = '0' ELSE
      temp_42;

  p25tmp_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 96);
  
  tmp_85 <= '1' WHEN p25tmp_cast > unsigned'(X"040000000000000000000000") ELSE
      '0';

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_trueregionp26
  temp_43 <= to_signed(16#00000006#, 32);

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_falseregionp22
  
  tmp_86 <= tmp_84 WHEN tmp_83 = '0' ELSE
      temp_43;

  p21tmp_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 96);
  
  tmp_87 <= '1' WHEN p21tmp_cast > unsigned'(X"080000000000000000000000") ELSE
      '0';

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_trueregionp22
  temp_44 <= to_signed(16#00000005#, 32);

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_falseregionp18
  
  tmp_88 <= tmp_86 WHEN tmp_85 = '0' ELSE
      temp_44;

  p17tmp_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 96);
  
  tmp_89 <= '1' WHEN p17tmp_cast > unsigned'(X"100000000000000000000000") ELSE
      '0';

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_trueregionp18
  temp_45 <= to_signed(16#00000004#, 32);

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_falseregionp14
  
  tmp_90 <= tmp_88 WHEN tmp_87 = '0' ELSE
      temp_45;

  p13tmp_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 96);
  
  tmp_91 <= '1' WHEN p13tmp_cast > unsigned'(X"200000000000000000000000") ELSE
      '0';

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_trueregionp14
  temp_46 <= to_signed(16#00000003#, 32);

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_falseregionp10
  
  tmp_92 <= tmp_90 WHEN tmp_89 = '0' ELSE
      temp_46;

  p9tmp_cast <= resize(x_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 96);
  
  tmp_93 <= '1' WHEN p9tmp_cast > unsigned'(X"400000000000000000000000") ELSE
      '0';

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_trueregionp10
  temp_47 <= to_signed(16#00000002#, 32);

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_falseregionp6
  
  tmp_94 <= tmp_92 WHEN tmp_91 = '0' ELSE
      temp_47;

  -- else
  -- 
  --     while( )
  -- 
  --         temp = temp+1;
  -- 
  --         flag()=flag()*2;
  -- 
  --     end
  -- 
  -- end
  -- 
  -- 
  -- 
  -- end
  
  tmp_95 <= '1' WHEN x_unsigned = to_unsigned(0, 48) ELSE
      '0';

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_trueregionp6
  temp_48 <= to_signed(16#00000001#, 32);

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_falseregionp2
  
  tmp_96 <= tmp_94 WHEN tmp_93 = '0' ELSE
      temp_48;

  -- HDL code generation from MATLAB function: sf_gateway_leadingZeroDetector_trueregionp2
  temp_49 <= to_signed(16#00000031#, 32);

  
  tmp_97 <= tmp_96 WHEN tmp_95 = '0' ELSE
      temp_49;

  exp_e_tmp <= unsigned(tmp_97(7 DOWNTO 0));

  exp_e <= std_logic_vector(exp_e_tmp);

END rtl;

